ALERT_FALL = "PATIENT_FALL_DETECTED"
ALERT_LOW_OXYGEN = "LOW_OXYGEN_SATURATION"
ALERT_NO_PATIENT = "PATIENT_NOT_VISIBLE"

SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_CRITICAL = "critical"
